(define version "1.0")
(define deps '("base"))

(define black        #(40 40 40))
(define white        #(235 219 178))
(define light-gray   #(168 153 132))
(define dark-gray    #(146 131 116))
(define red          #(204 36 29))
(define green        #(152 151 26))
(define light-yellow #(250 189 47))
(define dark-yellow  #(215 153 33))
(define blue         #(69 133 136))
(define magenta      #(177 98 134))
(define cyan         #(104 157 106))
  
(define framework:color-schemes
  `(#hash((name . "Gruvbox")
          (white-on-black-base? . #t)
          (colors
           .
	   ((drracket:error-background-highlighting                       ,red)
            (drracket:language-name-and-memory-use-at-top-of-interactions ,green)
            (drracket:syncheck:matching-identifiers                       ,dark-gray)
            (framework:basic-canvas-background                            ,black)
            (framework:default-text-color                                 ,white)
            (framework:line-numbers                                       ,light-gray)
            (framework:line-numbers-current-line-number-background        ,black)
            (framework:line-numbers-current-line-number-foreground        ,black)
            (framework:line-numbers-when-word-wrapping                    ,black)
            (framework:misspelled-text-color                              ,white)
            (framework:paren-match-color                                  ,dark-gray)
            (framework:program-contour-current-location-bar               ,dark-gray)
            (drracket:check-syntax:both-obligation-style-pref             ,light-yellow)
            (drracket:check-syntax:free-variable                          ,red)
            (drracket:check-syntax:imported                               ,magenta)
            (drracket:check-syntax:lexically-bound                        ,cyan)
            (drracket:check-syntax:my-obligation-style-pref               ,red)
            (drracket:check-syntax:set!d                                  ,red)
            (drracket:check-syntax:their-obligation-style-pref            ,green)
            (drracket:check-syntax:unk-obligation-style-pref              ,white)
            (drracket:check-syntax:unused-require                         ,red)
            (drracket:read-eval-print-loop:error-color                    ,red)
            (drracket:read-eval-print-loop:out-color                      ,green)
            (drracket:read-eval-print-loop:value-color                    ,blue)
            (framework:syntax-color:scheme:comment                        ,light-gray)
            (framework:syntax-color:scheme:constant                       ,dark-yellow)
            (framework:syntax-color:scheme:error                          ,red)
            (framework:syntax-color:scheme:hash-colon-keyword             ,dark-yellow)
            (framework:syntax-color:scheme:keyword                        ,magenta)
            (framework:syntax-color:scheme:other                          ,white)
            (framework:syntax-color:scheme:parenthesis                    ,white)
            (framework:syntax-color:scheme:string                         ,green)
            (framework:syntax-color:scheme:symbol                         ,blue)
            (framework:syntax-color:scheme:text                           ,green)
            (plt:htdp:test-coverage-off                                   ,red)
            (plt:htdp:test-coverage-on                                    ,white)
            (plt:module-language:test-coverage-off                        ,red)
            (plt:module-language:test-coverage-on                         ,white))))))
